version: '3.8'

services:

  # ================================
  # BOOKS
  # ================================
  livres-postgres:
    image: postgres:16
    container_name: livres-postgres
    environment:
      POSTGRES_DB: livresdb
      POSTGRES_USER: livresuser
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - livres_data:/var/lib/postgresql/data

  livres-service:
    build: .
    container_name: livres-service
    ports:
      - "8081:8080"
    depends_on:
      - livres-postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://livres-postgres:5432/livresdb
      SPRING_DATASOURCE_USERNAME: livresuser
      SPRING_DATASOURCE_PASSWORD: postgres


  # ================================
  # USERS
  # ================================
  users-postgres:
    image: postgres:16
    container_name: users-postgres
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: usersuser
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - users_data:/var/lib/postgresql/data

  users-service:
    build: ../userservice
    container_name: users-service
    ports:
      - "8082:8080"
    depends_on:
      - users-postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://users-postgres:5432/usersdb
      SPRING_DATASOURCE_USERNAME: usersuser
      SPRING_DATASOURCE_PASSWORD: postgres


  # ================================
  # LOANS
  # ================================
  loans-postgres:
    image: postgres:16
    container_name: loans-postgres
    environment:
      POSTGRES_DB: loansdb
      POSTGRES_USER: loansuser
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - loans_data:/var/lib/postgresql/data

  loans-service:
    build: ../loans-service
    container_name: loans-service
    ports:
      - "8083:8080"
    depends_on:
      - loans-postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://loans-postgres:5432/loansdb
      SPRING_DATASOURCE_USERNAME: loansuser
      SPRING_DATASOURCE_PASSWORD: postgres


  # ================================
  # NOTIFICATIONS
  # ================================
  notifications-postgres:
    image: postgres:16
    container_name: notifications-postgres
    environment:
      POSTGRES_DB: notifications_db
      POSTGRES_USER: notification_user
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - notifications_data:/var/lib/postgresql/data

  notification-service:
    build: ../notification_service
    container_name: notification-service
    ports:
      - "8084:8080"
    depends_on:
      - notifications-postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://notifications-postgres:5432/notifications_db
      SPRING_DATASOURCE_USERNAME: notification_user
      SPRING_DATASOURCE_PASSWORD: postgres


  # ================================
  # FRONTEND
  # ================================
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3001:80"
    depends_on:
      - livres-service
      - users-service
      - loans-service
      - notification-service


volumes:
  livres_data:
  users_data:
  loans_data:
  notifications_data: